[
    uuid(12345678-1234-1234-1234-123456789012),
    version(1.0),
    pointer_default(unique)
]
interface ITrayService
{
    void StopService(void);
    void GetServiceStatus([out] long *status);
};
